parameters:
    result_error:                    'error'
    result_success:                  'success'
    result_exists:                   'exists'

    message_user_created:            'User created!'
    message_user_allready_created:   'User already created!'
    message_user_updated:            'User updated!'
    message_activity_created:        'Stair Activity created!'
    message_activity_updated:        'Stair Activity updated!'
    message_wrong_date:              'Wrong date type'
    message_wrong_email_or_password: 'Wrong email-password combination'
    message_activities_returned:     'Activities returned!'
    message_activity_deletion:       'Stair Activity marked for deletion!'
    message_no_activity_found:       'No stair activity found'
    message_teams_returned:          'Teams returned!'
    message_team_returned:           'Team returned!'
    message_team_no_members:         'Wrong team id or no team members'
    team_name_taken:                 'Team name already taken'
    message_team_created:            'Team created!'
    team_name_not_found:             'Team not found'
    message_team_joined:             'Joined team!'
    message_team_left:               'Left team!'
    message_team_no_user:            'User not found in team'
    message_team_left_owner:         'Cannot leave because you are the owner!'
    message_team_already_joined:     'You are already part of the team'
    message_stats_returned:          'Stats returned!'
    message_stats_not_returned:      'Stats not returned!'

    api_top_url:                     '/api/stairactivity/top'
    api_user_url:                    '/api/user/create'

    google_api_key:                  '123456'
    google_gcm_url:                  'https://android.googleapis.com/gcm/send'
