imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    router:   { resource: "%kernel.root_dir%/config/routing_test.yml" }
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver2%
        host:     %database_host2%
        port:     %database_port2%
        dbname:   %database_name2%
        user:     %database_user2%
        password: %database_password2%
        charset:  UTF8
        path: %kernel.cache_dir%/test.db 