IBW\WebsiteBundle\Entity\User:
    type: entity
    repositoryClass: IBW\WebsiteBundle\Repository\UserRepository
    table: user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        email:
            type: string
            length: 50
        password:
            type: string
            length: 100
        updated_at:
            type: datetime 
        created_at:
            type: datetime
    oneToMany:
        stairs_activities:
            targetEntity: StairsActivity
            mappedBy: user
        user_teams:
            targetEntity: UserTeam
            mappedBy: user      
        owned_teams:
            targetEntity: Team
            mappedBy: owner
        gcm_devices:
            targetEntity: GcmDevice
            mappedBy: user
            
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue, setUpdatedAtValue ]
        preUpdate:  [ setUpdatedAtValue ]
